### PR TITLE
first draft of XSLT sheet for the elsevier xml reader

### PR DESCRIPTION
**Pull request by jibe-b**
@rbossy This draft is not fully correct but I place it here to get comments on the lines you think I should improve.

### CODE REVIEW

**Comment by jibe-b** [comment]
Well, this commit doesn't pass the tests, so this PR should stay unmerged until it passes tests.

**Comment by rbossy** [comment]
Test aren't supposed to pass anyway. Some tests are not deterministic, for reasons.

**Comment by jibe-b** [comment]
Hum, well, I can deterministically say that this version of this XSL sheet is not finished and will not be usable…

**Comment by rbossy** [comment]
Ah. Not a big problem since nobody's aware of this.

Then, request a pull again when it is minimally functional.

**Pull request merged**
